{% set name = "hologram" %}
{% set version = "0.0.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hologram-{{ version }}.tar.gz
  sha256: 79b3d04df84d5a9d09c2e669ec5bcc50b1713ec79f4683cfdea85583b41e46f0

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses >=0.6,<0.9
    - jsonschema >=3.0
    - python >=3.6
    - python-dateutil >=2.8,<2.9

test:
  imports:
    - hologram

about:
  home: https://github.com/fishtown-analytics/hologram
  summary: JSON schema generation from dataclasses
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
