{% set version = "0.0.15" %}


package:
  name: hologram
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/h/hologram/hologram-{{ version }}.tar.gz
    sha256: 79b3d04df84d5a9d09c2e669ec5bcc50b1713ec79f4683cfdea85583b41e46f0
    patches:
      - 0000-relax-json-schema-pin.patch
  - folder: src
    url: https://github.com/dbt-labs/hologram/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 5c9c04c6dd22d2cebb9d1ff156f462ef350e8d6ba08294ce8940fc3b2841b9c9
    patches:
      - 0001-use-default-factory.patch

build:
  noarch: python
  number: 2
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses >=0.6,<0.9
    - jsonschema >=3.0
    - python >=3.6
    - python-dateutil >=2.8,<2.9

test:
  source_files:
    - src/tests
  requires:
    - pip
    - pytest-cov
  imports:
    - hologram
  commands:
    - pip check
    - pytest -vv src/tests --cov=hologram --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=90

about:
  home: https://github.com/fishtown-analytics/hologram
  summary: JSON schema generation from dataclasses
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - thewchan
